# Generated by Django 4.2.1 on 2023-05-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0002_automoviles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
    ]
