# Generated by Django 4.2.1 on 2023-05-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0003_clientes_sucursales'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='directorio/'),
        ),
    ]
