# Generated by Django 4.2.1 on 2023-05-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postres', '0006_alter_producto_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(max_length=200),
        ),
    ]
